BEGIN TRANSACTION;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
     id SERIAL PRIMARY KEY,
     full_name VARCHAR(100) NOT NULL,
     email VARCHAR(100) UNIQUE NOT NULL,
     password_hash VARCHAR(255) NOT NULL,
     phone VARCHAR(20),
     role VARCHAR(20) CHECK (role IN ('CUSTOMER', 'SERVICE_PROVIDER', 'ADMIN')) NOT NULL,
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMIT TRANSACTION;

